# Generated by Django 4.2.7 on 2026-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('original_title', models.TextField(verbose_name='Orijinal Baslik')),
                ('turkish_title', models.TextField(verbose_name='Turkce Baslik')),
                ('original_description', models.TextField(blank=True, verbose_name='Orijinal Aciklama')),
                ('turkish_description', models.TextField(blank=True, verbose_name='Turkce Aciklama')),
                ('turkish_summary', models.TextField(blank=True, verbose_name='Turkce Ozet')),
                ('link', models.URLField(verbose_name='Link')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('original_date', models.CharField(max_length=100, verbose_name='Orijinal Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
