# Generated by Django 4.2.7 on 2026-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True, verbose_name='CVE ID')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('original_title', models.TextField(verbose_name='Orijinal Baslik')),
                ('turkish_title', models.TextField(blank=True, verbose_name='Turkce Baslik')),
                ('original_description', models.TextField(verbose_name='Orijinal Aciklama')),
                ('turkish_description', models.TextField(blank=True, verbose_name='Turkce Aciklama')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='Siddet')),
                ('cvss_score', models.FloatField(blank=True, null=True, verbose_name='CVSS Skoru')),
                ('published_date', models.DateField(verbose_name='Yayinlanma Tarihi')),
                ('modified_date', models.DateField(blank=True, null=True, verbose_name='Guncelleme Tarihi')),
                ('link', models.URLField(verbose_name='Link')),
                ('cwe_ids', models.JSONField(blank=True, default=list, verbose_name='CWE IDleri')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='Referanslar')),
                ('affected_products', models.TextField(blank=True, verbose_name='Etkilenen Urunler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name': 'CVE Kaydi',
                'verbose_name_plural': 'CVE Kayitlari',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
