# Generated by Django 4.2.7 on 2026-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_kubernetesentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SREEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('original_title', models.TextField(verbose_name='Orijinal Baslik')),
                ('turkish_title', models.TextField(blank=True, verbose_name='Turkce Baslik')),
                ('original_description', models.TextField(verbose_name='Orijinal Aciklama')),
                ('turkish_description', models.TextField(blank=True, verbose_name='Turkce Aciklama')),
                ('link', models.URLField(max_length=500, unique=True, verbose_name='Link')),
                ('published_date', models.DateField(verbose_name='Yayinlanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name': 'SRE Haberi',
                'verbose_name_plural': 'SRE Haberleri',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
