# Generated by Django 4.2.7 on 2026-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_sreentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevToolsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('original_title', models.TextField(verbose_name='Orijinal Baslik')),
                ('turkish_title', models.TextField(blank=True, verbose_name='Turkce Baslik')),
                ('original_description', models.TextField(verbose_name='Orijinal Aciklama')),
                ('turkish_description', models.TextField(blank=True, verbose_name='Turkce Aciklama')),
                ('link', models.URLField(max_length=500, unique=True, verbose_name='Link')),
                ('published_date', models.DateField(verbose_name='Yayinlanma Tarihi')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Surum')),
                ('entry_type', models.CharField(choices=[('release', 'Release'), ('blog', 'Blog'), ('news', 'News')], default='release', max_length=20, verbose_name='Tur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
            ],
            options={
                'verbose_name': 'DevTools Guncellemesi',
                'verbose_name_plural': 'DevTools Guncellemeleri',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
